import ExcelJS from 'exceljs';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { getTimetable } from './timetable';
import db from '../models/db';

const daysOfWeek = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"];
const periodLabels = [
  "P1 (8:50 - 9:40)",
  "P2 (9:40 - 10:30)",
  "P3 (10:40 - 11:30)",
  "P4 (11:30 - 12:20)",
  "P5 (12:20 - 1:10)",
  "P6 (1:10 - 2:00)",
  "P7 (2:00 - 2:50)",
  "P8 (2:50 - 3:40)",
  "P9 (3:40 - 4:30)"
];

// Helper to determine row index in Excel/PDF grids
const getExcelRowIdx = (slotIndex: number) => {
  return 5 + slotIndex;
};

/**
 * Helper to fetch and group timetable slots based on section or faculty
 */
async function fetchGroupedSlots(
  type: "section" | "all" | "faculty",
  branchId?: string,
  year?: number,
  sectionName?: string,
  facultyId?: string
) {
  // Query all slots matching filters
  const slots = await getTimetable({
    branchId: type === 'section' ? branchId : undefined,
    year: type === 'section' ? year : undefined,
    section: type === 'section' ? sectionName : undefined
  });

  const groups: { [key: string]: { label: string; info: string; slots: any[] } } = {};

  if (type === 'faculty') {
    // Group by Faculty
    const faculties = await db.faculty.findMany();
    
    for (const fac of faculties) {
      if (facultyId && fac.id !== facultyId) continue;

      const facultySlots = slots.filter((s: any) => s.facultyId === fac.id);
      
      // Only export faculty with scheduled slots
      if (facultySlots.length > 0) {
        groups[fac.name] = {
          label: `Faculty Schedule: ${fac.name}`,
          info: `Department: ${fac.department} | Source: ${fac.source}`,
          slots: facultySlots
        };
      }
    }
  } else {
    // Group by Section
    for (const slot of slots) {
      const section = slot.section || slot.labBatch?.section;
      if (!section) continue;

      // Filter by section name if exporting a single section
      if (type === 'section' && sectionName && section.sectionName !== sectionName) continue;
      // Filter by year if exporting a single year
      if (type === 'section' && year && section.year.yearNumber !== year) continue;

      const key = `${section.year.branch.code}_Yr${section.year.yearNumber}_Sec${section.sectionName}`;
      if (!groups[key]) {
        groups[key] = {
          label: `${section.year.branch.code} - Year ${section.year.yearNumber} (Sec ${section.sectionName})`,
          info: `Branch: ${section.year.branch.name} | Strength: ${section.strength} students`,
          slots: []
        };
      }
      groups[key].slots.push(slot);
    }
  }

  return groups;
}

/**
 * Generates an Excel workbook buffer using exceljs
 */
export async function generateExcelBuffer(
  type: "section" | "all" | "faculty" = "section",
  branchId?: string,
  year?: number,
  sectionName?: string,
  facultyId?: string
): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  const groups = await fetchGroupedSlots(type, branchId, year, sectionName, facultyId);

  // If no data exists, add an empty sheet
  if (Object.keys(groups).length === 0) {
    const ws = workbook.addWorksheet('No Data');
    ws.getCell('A1').value = 'No timetable slots scheduled matching these criteria.';
  }

  for (const [key, group] of Object.entries(groups)) {
    // Sheet name length limit: 31 characters
    const ws = workbook.addWorksheet(key.substring(0, 31).replace(/[:*?/\\\[\]]/g, "_"));

    // Set Column Widths
    ws.getColumn(1).width = 24; // Timeslot column
    for (let i = 2; i <= 6; i++) ws.getColumn(i).width = 22; // Monday-Friday columns

    // 1. Header titles
    ws.mergeCells('A1:F1');
    const titleCell = ws.getCell('A1');
    titleCell.value = 'ENGINEERING COLLEGE TIMETABLE';
    titleCell.font = { name: 'Arial', size: 16, bold: true, color: { argb: 'FFFFFF' } };
    titleCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: '312E81' } }; // Indigo-900
    titleCell.alignment = { horizontal: 'center', vertical: 'middle' };
    ws.getRow(1).height = 40;

    ws.mergeCells('A2:F2');
    const infoCell = ws.getCell('A2');
    infoCell.value = `${group.label}  |  ${group.info}`;
    infoCell.font = { name: 'Arial', size: 11, italic: true };
    infoCell.alignment = { horizontal: 'center', vertical: 'middle' };
    ws.getRow(2).height = 20;

    ws.mergeCells('A3:F3');
    const dateCell = ws.getCell('A3');
    dateCell.value = `Effective From: Academic Year 2026  |  Generated by AI Constraint Engine`;
    dateCell.font = { name: 'Arial', size: 9, color: { argb: '6B7280' } };
    dateCell.alignment = { horizontal: 'center', vertical: 'middle' };
    ws.getRow(3).height = 18;

    // 2. Table Column Headers
    const headers = ['Time Slot', ...daysOfWeek];
    ws.getRow(4).values = headers;
    ws.getRow(4).height = 25;
    
    // Header Style
    for (let i = 1; i <= 6; i++) {
      const cell = ws.getCell(4, i);
      cell.font = { name: 'Arial', size: 10, bold: true, color: { argb: 'FFFFFF' } };
      cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: '4F46E5' } }; // Indigo-600
      cell.alignment = { horizontal: 'center', vertical: 'middle' };
      cell.border = {
        top: { style: 'thin' }, bottom: { style: 'medium' },
        left: { style: 'thin' }, right: { style: 'thin' }
      };
    }

    // Find section details to get lunch index
    const sampleSlot = group.slots[0];
    const secObj = sampleSlot?.section || sampleSlot?.labBatch?.section;
    const groupLunchSlotIdx = secObj?.lunchSlotIndex !== undefined ? secObj.lunchSlotIndex : 4;

    // Initialize Grid Cells with "Free Period"
    for (let slotIdx = 0; slotIdx < 9; slotIdx++) {
      const rowIdx = 5 + slotIdx;
      const row = ws.getRow(rowIdx);
      row.height = 42;

      ws.getCell(rowIdx, 1).value = periodLabels[slotIdx];
      ws.getCell(rowIdx, 1).font = { name: 'Arial', size: 9, bold: true };
      ws.getCell(rowIdx, 1).alignment = { horizontal: 'center', vertical: 'middle', wrapText: true };
      ws.getCell(rowIdx, 1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'F1F5F9' } }; // Slate-100

      for (let dayCol = 2; dayCol <= 6; dayCol++) {
        const cell = ws.getCell(rowIdx, dayCol);
        cell.value = "Free Period";
        cell.font = { name: 'Arial', size: 9, italic: true, color: { argb: '94A3B8' } };
        cell.alignment = { horizontal: 'center', vertical: 'middle' };
        cell.border = {
          top: { style: 'thin' }, bottom: { style: 'thin' },
          left: { style: 'thin' }, right: { style: 'thin' }
        };
      }
    }

    // Set Lunch Row dynamically
    const lunchRowIdx = 5 + groupLunchSlotIdx;
    ws.mergeCells(`A${lunchRowIdx}:F${lunchRowIdx}`);
    const lunchCell = ws.getCell(`A${lunchRowIdx}`);
    lunchCell.value = 'LUNCH PERIOD';
    lunchCell.font = { name: 'Arial', size: 10, bold: true, color: { argb: '475569' }, italic: true };
    lunchCell.alignment = { horizontal: 'center', vertical: 'middle' };
    lunchCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'E2E8F0' } }; // Slate-200
    ws.getRow(lunchRowIdx).height = 20;

    // Track merged cells to avoid overriding values
    const mergedRanges = new Set<string>();

    // 3. Populate Slots Data
    for (const slot of group.slots) {
      const dayCol = slot.timeSlot.day + 2; // Col 2 is Monday
      const startSlotIdx = slot.timeSlot.slotIndex;
      const startRowIdx = getExcelRowIdx(startSlotIdx);
      
      // Determine duration (Default to 1 for section-level, or query lab batch/subject properties)
      const duration = (slot.subject.weeklyLabHours && (slot.labBatch || slot.subject.weeklyLabHours > 1)) 
        ? slot.subject.weeklyLabHours 
        : 1;

      const endRowIdx = getExcelRowIdx(startSlotIdx + duration - 1);
      
      // Create cell text representation
      const batchLabel = slot.labBatch ? `[${slot.labBatch.name}] ` : "";
      const facultyText = slot.assistantFaculty 
        ? `${slot.faculty.name} + ${slot.assistantFaculty.name}` 
        : slot.faculty.name;
      const textVal = `${batchLabel}${slot.subject.code}\n${slot.subject.name}\nRoom: ${slot.room.name}\nFaculty: ${facultyText}`;

      // Handle Merging
      if (duration > 1) {
        ws.mergeCells(startRowIdx, dayCol, endRowIdx, dayCol);
      }

      // Format merged block
      for (let r = startRowIdx; r <= endRowIdx; r++) {
        const cell = ws.getCell(r, dayCol);
        cell.value = textVal;
        cell.alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };

        // Color coding
        const isTraining = slot.subject.type === "TRAINING";
        const isLab = slot.subject.weeklyLabHours > 0 || slot.labBatchId !== null;

        if (isTraining) {
          cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'F3E8FF' } }; // Purple-100
          cell.font = { name: 'Arial', size: 9, bold: true, color: { argb: '6B21A8' } }; // Purple-800
          cell.border = {
            top: { style: 'thin' }, bottom: { style: 'thin' },
            left: { style: 'thin' }, right: { style: 'thin' }
          };
        } else if (isLab) {
          cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'CCFBF1' } }; // Teal-100
          cell.font = { name: 'Arial', size: 9, bold: true, color: { argb: '0F766E' } }; // Teal-800
        } else {
          cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'E0E7FF' } }; // Indigo-100
          cell.font = { name: 'Arial', size: 9, bold: true, color: { argb: '3730A3' } }; // Indigo-800
        }
      }
    }

    // 4. Draw Legend table at the bottom
    // Build unique subject records for the legend
    const uniqueSubjects = new Map<string, { name: string; faculty: string }>();
    for (const slot of group.slots) {
      const facName = slot.assistantFaculty 
        ? `${slot.faculty.name} + ${slot.assistantFaculty.name}` 
        : slot.faculty.name;
      uniqueSubjects.set(slot.subject.code, {
        name: slot.subject.name,
        faculty: facName
      });
    }

    const legendStartRow = 15;
    ws.getCell(legendStartRow, 1).value = 'COURSE / SUBJECT LEGEND';
    ws.getCell(legendStartRow, 1).font = { name: 'Arial', size: 11, bold: true, color: { argb: '1E293B' } };
    
    ws.getRow(legendStartRow + 1).values = ['Code', 'Subject Title', 'Assigned Instructor', '', '', '', ''];
    ws.getRow(legendStartRow + 1).font = { name: 'Arial', size: 9, bold: true };
    ws.mergeCells(legendStartRow + 1, 2, legendStartRow + 1, 4); // merge columns for spacing
    
    let currentLegendRow = legendStartRow + 2;
    for (const [code, info] of uniqueSubjects.entries()) {
      ws.getRow(currentLegendRow).height = 18;
      ws.getCell(currentLegendRow, 1).value = code;
      ws.getCell(currentLegendRow, 1).font = { name: 'Arial', size: 9, bold: true };
      
      ws.getCell(currentLegendRow, 2).value = info.name;
      ws.getCell(currentLegendRow, 2).font = { name: 'Arial', size: 9 };
      ws.mergeCells(currentLegendRow, 2, currentLegendRow, 4);

      ws.getCell(currentLegendRow, 5).value = info.faculty;
      ws.getCell(currentLegendRow, 5).font = { name: 'Arial', size: 9, italic: true };
      ws.mergeCells(currentLegendRow, 5, currentLegendRow, 7);

      currentLegendRow++;
    }
  }

  // Generate buffer and return
  const buffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(buffer);
}

/**
 * Generates a PDF buffer using jsPDF + jsPDF-AutoTable
 */
export async function generatePdfBuffer(
  type: "section" | "all" | "faculty" = "section",
  branchId?: string,
  year?: number,
  sectionName?: string,
  facultyId?: string
): Promise<Buffer> {
  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4'
  });

  const groups = await fetchGroupedSlots(type, branchId, year, sectionName, facultyId);
  const groupKeys = Object.keys(groups);

  if (groupKeys.length === 0) {
    doc.setFont("Helvetica", "bold");
    doc.setFontSize(14);
    doc.text("No timetable data found matching criteria.", 15, 20);
    return Buffer.from(doc.output('arraybuffer'));
  }

  groupKeys.forEach((key, idx) => {
    const group = groups[key];
    if (idx > 0) doc.addPage();

    // 1. Draw header placeholder
    doc.setFillColor(49, 46, 145); // Indigo 900
    doc.rect(12, 10, 273, 16, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFont("Helvetica", "bold");
    doc.setFontSize(14);
    doc.text("ENGINEERING COLLEGE TIMETABLE", 16, 20);

    doc.setTextColor(51, 65, 85);
    doc.setFontSize(10);
    doc.setFont("Helvetica", "oblique");
    doc.text(`${group.label}  |  ${group.info}`, 14, 32);

    doc.setFont("Helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text("Effective: July 2026  |  Auto-Generated by AI Solver", 14, 37);

    // 2. Construct body rows for autoTable
    const tableBody: any[] = [];
    
    // Track rowSpans to skip writing cells that are occupied by a merged slot
    const rowSpanTracker: Record<string, number> = {}; // Key: "colIndex_periodIndex" -> value represents remaining rows to skip

    const sampleSlot = group.slots[0];
    const secObj = sampleSlot?.section || sampleSlot?.labBatch?.section;
    const groupLunchSlotIdx = secObj?.lunchSlotIndex !== undefined ? secObj.lunchSlotIndex : 4;

    for (let slotIdx = 0; slotIdx < 9; slotIdx++) {
      const rowData: any[] = [periodLabels[slotIdx]];

      if (slotIdx === groupLunchSlotIdx) {
        // Lunch Hour
        rowData.push({
          content: "LUNCH PERIOD",
          colSpan: 5,
          styles: { 
            halign: "center", 
            valign: "middle", 
            fillColor: [226, 232, 240], // Slate-200
            textColor: [71, 85, 105],
            fontStyle: "bolditalic"
          }
        });
        tableBody.push(rowData);
        continue;
      }

      for (let d = 0; d < 5; d++) {
        const trackerKey = `${d}_${slotIdx}`;
        if (rowSpanTracker[trackerKey] && rowSpanTracker[trackerKey] > 0) {
          // Decrement and skip adding cell
          rowSpanTracker[trackerKey]--;
          continue;
        }

        // Find slots scheduled at this day and period
        const matched = group.slots.filter((s: any) => s.timeSlot.day === d && s.timeSlot.slotIndex === slotIdx);

        if (matched.length > 0) {
          const slot = matched[0]; // Take the first parallel slot for cell display
          const isTraining = slot.subject.type === "TRAINING";
          const isLab = slot.subject.weeklyLabHours > 0 || slot.labBatchId !== null;

          const duration = (slot.subject.weeklyLabHours && (slot.labBatch || slot.subject.weeklyLabHours > 1))
            ? slot.subject.weeklyLabHours
            : 1;

          // Color palette selection
          let fillColor = [224, 231, 255]; // Indigo-100 (Academic)
          let textColor = [55, 48, 163];
          if (isTraining) {
            fillColor = [243, 232, 255]; // Purple-100
            textColor = [107, 33, 168];
          } else if (isLab) {
            fillColor = [204, 251, 241]; // Teal-100
            textColor = [15, 118, 110];
          }

          // If duration > 1, register rowSpan in tracker for future periods in this column
          if (duration > 1) {
            for (let next = 1; next < duration; next++) {
              rowSpanTracker[`${d}_${slotIdx + next}`] = 1;
            }
          }

          const batchLabel = slot.labBatch ? `[${slot.labBatch.name}] ` : "";
          const facText = slot.assistantFaculty 
            ? `${slot.faculty.name.split(' ')[0]} + ${slot.assistantFaculty.name.split(' ')[0]}` 
            : slot.faculty.name.split(' ')[0];

          rowData.push({
            content: `${batchLabel}${slot.subject.code}\n${slot.subject.name}\n${slot.room.name}\n${facText}`,
            rowSpan: duration,
            styles: {
              fillColor,
              textColor,
              fontSize: 7.5,
              fontStyle: "bold",
              halign: "center",
              valign: "middle"
            }
          });
        } else {
          rowData.push({
            content: "Free Period",
            styles: {
              textColor: [148, 163, 184],
              fontStyle: "italic",
              halign: "center",
              valign: "middle",
              fontSize: 7
            }
          });
        }
      }

      tableBody.push(rowData);
    }

    // 3. Draw grid table
    autoTable(doc, {
      startY: 40,
      margin: { left: 12, right: 12 },
      head: [['Period Time', ...daysOfWeek]],
      body: tableBody,
      theme: 'grid',
      headStyles: {
        fillColor: [79, 70, 229], // Indigo-600
        fontSize: 9,
        halign: 'center'
      },
      styles: {
        cellPadding: 1.5,
        lineWidth: 0.15,
        lineColor: [226, 232, 240] // border line Slate-200
      },
      columnStyles: {
        0: { cellWidth: 35, fontStyle: 'bold', fillColor: [248, 250, 252] } // First column width
      }
    });

    // 4. Draw legend at the bottom of the page
    const uniqueSubjects = new Map<string, { name: string; faculty: string }>();
    for (const slot of group.slots) {
      const facName = slot.assistantFaculty 
        ? `${slot.faculty.name} + ${slot.assistantFaculty.name}` 
        : slot.faculty.name;
      uniqueSubjects.set(slot.subject.code, {
        name: slot.subject.name,
        faculty: facName
      });
    }

    const startY = (doc as any).lastAutoTable.finalY + 8;
    if (startY < 195) { // Ensure there is enough vertical space remaining on page
      doc.setTextColor(30, 41, 59);
      doc.setFontSize(9);
      doc.setFont("Helvetica", "bold");
      doc.text("COURSE LEGEND", 14, startY);

      doc.setFont("Helvetica", "normal");
      doc.setFontSize(7.5);
      
      let xOffset = 14;
      let yOffset = startY + 4.5;
      
      for (const [code, info] of uniqueSubjects.entries()) {
        if (xOffset > 240) {
          xOffset = 14;
          yOffset += 4;
        }
        
        doc.setFont("Helvetica", "bold");
        doc.text(`${code}: `, xOffset, yOffset);
        
        const widthOfCode = doc.getTextWidth(`${code}: `);
        doc.setFont("Helvetica", "normal");
        doc.text(`${info.name} (${info.faculty.split(' ')[0]})    |    `, xOffset + widthOfCode, yOffset);
        
        xOffset += widthOfCode + doc.getTextWidth(`${info.name} (${info.faculty.split(' ')[0]})    |    `);
      }
    }
  });

  const buffer = doc.output('arraybuffer');
  return Buffer.from(buffer);
}
